title: SyncDPO
description: Improving Temporal Alignment in Video-Audio Joint Generation via Preference Optimization

url: https://syncdpo.github.io
baseurl:
paginate_path: "blog/page:num/"
permalink: blog/:title/

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /home
    - title: Samples
      url: /samples
    - title: About
      url: /about
    - title: Code
      url: /code

google_analytics: ""

disqus:
    shortname: ""
